[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

; Velocidad del monitor serie
monitor_speed = 115200

; Activar el USB CDC para que Serial.print funcione por el USB nativo del C3
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1